name: flutter_mana
description: "Mana is an in-app debug kits platform for Flutter. Flutter应用内调试工具平台"
version: 1.0.0-beta.5
homepage: https://github.com/lhlyu/flutter_mana

environment:
  sdk: ">=2.19.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  device_info_plus: ^9.1.2
  dio: ^5.1.1
  logger: ^1.3.0
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

